name: space_data_api
dependencies:
  - python==3.12.*
  - numpy
  - fastapi
  - passlib
  - python-multipart
  - apscheduler
  - uvicorn
  - spiceypy
  - requests
  - beautifulsoup4
  - pytest
  - pytest-asyncio
  - pip:
      -pyseto
